### PR TITLE
21 Enable Account creation and login via REST API

### PR DESCRIPTION
**Pull request by Xyntlock**
- Added 2 POST endpoints
  - One for login
  - One for account creation
- Prevents account with same username as existing account from being created 
- Hashes password in DB using 'bcrypt' for security#
- Adds login functionality to app login page

### CODE REVIEW

**Comment by EmKaaaM** [comment]
The app builds and takes me to the login screen however I can't login with either of the test credentials. 
I have installed npm and ran npm install, the API is running while im trying to login. When I launch the app and try to I get Incorrect Password for both credentials even though api is running.

Also the API can't be run on a windows machine it has to be done through linux.

 The instructions provided did not allow me to successfully login.

**Comment by EmKaaaM** [comment]
The Error that happens when running `npm start` in a windows shell

PS E:\UniWork\SQA\MindScribe\code\API> npm start
```
> api@1.0.0 start
> node server.js

node:internal/modules/cjs/loader:1473
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: \\?\E:\UniWork\SQA\MindScribe\code\API\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node is not a valid Win32 application.
\\?\E:\UniWork\SQA\MindScribe\code\API\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (E:\UniWork\SQA\MindScribe\code\API\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by EmKaaaM** [comment]
Problem was with a node_modules, needed to delete it and run `npm install` and I was able to connect to both credentials.

However when home button is pressed the app does crash
```
2023-11-25 13:43:18.835  5133-5133  AndroidRuntime          com.example.mindscribe               E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.mindscribe, PID: 5133
                                                                                                    java.lang.IllegalStateException: Could not find method onHomeBtnClick(View) in a parent or ancestor Context for android:onClick attribute defined on view class com.google.android.material.button.MaterialButton with id 'homeBtn'
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:506)
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:464)
                                                                                                    	at android.view.View.performClick(View.java:7455)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1213)
                                                                                                    	at android.view.View.performClickInternal(View.java:7432)
                                                                                                    	at android.view.View.access$3700(View.java:835)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28810)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                      
```

Might be worth a seperate issue though

**Review by EmKaaaM — APPROVED** [review]
Works fine after deleting node_modules and running npm install.

**Comment by Xyntlock** [comment]
I think that's a separate issue. This MR doesn't touch the home button navigation.

**Pull request merged**
